[package]
name = "wstcpproxy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base64 = { version = "0.22.1", features = [] }
bytes = "1.10.1"
fastwebsockets = "0.10.0"
nom = "8.0.0"
sha1_smol = "1.0.1"
tokio = { version = "1", features = ["full"] }
